name: token test

on: 
  push
  
jobs:
  tests_manual_workflow:
    runs-on: ubuntu-latest
    steps:
    - run: >
      env:
       TEST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       TEST_SECRET: ${{ secrets.TEST_SECRET }}

    - run: |
          echo ${#TEST_GITHUB_TOKEN}
          echo ${#TEST_SECRET}
